name: Lint Python Code

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: true  # Нужно для git push

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black ruff flake8 pylint pylint-peewee

    - name: Check if this is a fork
      id: fork-check
      run: |
        echo "IS_FORK=false" >> "$GITHUB_ENV"
        if [ "${{ github.repository }}" != "${{ github.event.pull_request.head.repo.full_name }}" ]; then
          echo "IS_FORK=true" >> "$GITHUB_ENV"
        fi

    - name: Format code with black and ruff
      if: env.IS_FORK == 'false'
      run: |
        black .
        ruff check . --fix

    - name: Run flake8
      if: env.IS_FORK == 'false'
      run: flake8 .

    - name: Run pylint
      if: env.IS_FORK == 'false'
      run: pylint $(find . -name "*.py" ! -path "./venv/*")

    - name: Commit and push changes (only if not a fork)
      if: env.IS_FORK == 'false'
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

        if [[ $(git status --porcelain) ]]; then
          git add .
          git commit -m "chore: auto-fix formatting via GitHub Actions"
          git push
        else
          echo "No changes to commit."
        fi
